/* Generated by scripts/maintenance/build-maintenance.js; verification facts remain in data.js.
   On-demand data uses var: a late request from before a retry may still execute, and running twice only reassigns the same data. */
var MAINTENANCE = {
  "schemaVersion": 1,
  "generatedAt": "2026-10-09",
  "checkedThrough": "2026-10-09",
  "staleAfterDays": 14,
  "rssSite": "https://coding-plan-comparison-tau.vercel.app/",
  "inputHashes": {
    "data": "398c7b58a4c4e2f725720c57991d2482ae01f556f5030ce3dbfee17d5bad6836",
    "history": "baaaed71f81b976497cbe4898ffab6b5935d17422490a51a76722547286baa86",
    "calendar": "c59316c1df1af85df4bfe1e41dd78a01d089f6806e32f52e499111fe0fa1ed26"
  },
  "summary": {
    "total": 258,
    "verified": 218,
    "unverified": 24,
    "stale": 0
  },
  "records": [
    {
      "id": "plan-0001",
      "kind": "plan",
      "vendor": "Anthropic",
      "name": "Claude Free",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://claude.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0002",
      "kind": "plan",
      "vendor": "Anthropic",
      "name": "Claude Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://claude.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0003",
      "kind": "plan",
      "vendor": "Anthropic",
      "name": "Claude Max 5x",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://support.claude.com/en/articles/11049741-what-is-the-max-plan"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0004",
      "kind": "plan",
      "vendor": "Anthropic",
      "name": "Claude Max 20x",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://support.claude.com/en/articles/11049741-what-is-the-max-plan"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0005",
      "kind": "plan",
      "vendor": "Anthropic",
      "name": "Claude Team（标准席位）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://claude.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0006",
      "kind": "plan",
      "vendor": "Anthropic",
      "name": "Claude Team（Premium 席位）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://claude.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0007",
      "kind": "plan",
      "vendor": "Anthropic",
      "name": "Claude Enterprise",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://claude.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0008",
      "kind": "plan",
      "vendor": "OpenAI",
      "name": "ChatGPT Free",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://learn.chatgpt.com/docs/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0009",
      "kind": "plan",
      "vendor": "OpenAI",
      "name": "ChatGPT Go",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://learn.chatgpt.com/docs/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0010",
      "kind": "plan",
      "vendor": "OpenAI",
      "name": "ChatGPT Plus",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://learn.chatgpt.com/docs/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0011",
      "kind": "plan",
      "vendor": "OpenAI",
      "name": "ChatGPT Pro（$100）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://learn.chatgpt.com/docs/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0012",
      "kind": "plan",
      "vendor": "OpenAI",
      "name": "ChatGPT Pro（$200）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://learn.chatgpt.com/docs/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0013",
      "kind": "plan",
      "vendor": "OpenAI",
      "name": "ChatGPT Pro（$500）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://learn.chatgpt.com/docs/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0014",
      "kind": "plan",
      "vendor": "OpenAI",
      "name": "ChatGPT Business",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://learn.chatgpt.com/docs/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0015",
      "kind": "plan",
      "vendor": "OpenAI",
      "name": "ChatGPT Enterprise",
      "checkedAt": "2026-10-04",
      "status": "custom",
      "sourceUrls": [
        "https://learn.chatgpt.com/docs/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0016",
      "kind": "plan",
      "vendor": "Google",
      "name": "Google AI Plus",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://one.google.com/about/google-ai-plans/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0017",
      "kind": "plan",
      "vendor": "Google",
      "name": "Google AI Pro",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://one.google.com/about/google-ai-plans/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0018",
      "kind": "plan",
      "vendor": "Google",
      "name": "Google AI Ultra（5x）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://one.google.com/about/google-ai-plans/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0019",
      "kind": "plan",
      "vendor": "Google",
      "name": "Google AI Ultra（20x）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://one.google.com/about/google-ai-plans/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0020",
      "kind": "plan",
      "vendor": "Google",
      "name": "Gemini CLI / Code Assist 个人免费版",
      "checkedAt": "2026-10-09",
      "status": "retired",
      "sourceUrls": [
        "https://developers.googleblog.com/an-important-update-transitioning-gemini-cli-to-antigravity-cli/"
      ],
      "ageDays": 0,
      "stale": false
    },
    {
      "id": "plan-0021",
      "kind": "plan",
      "vendor": "Google",
      "name": "Gemini Code Assist Standard",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://codeassist.google/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0022",
      "kind": "plan",
      "vendor": "Google",
      "name": "Gemini Code Assist Enterprise",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://codeassist.google/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0023",
      "kind": "plan",
      "vendor": "xAI",
      "name": "Grok Free",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://x.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0024",
      "kind": "plan",
      "vendor": "xAI",
      "name": "SuperGrok Lite",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://x.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0025",
      "kind": "plan",
      "vendor": "xAI",
      "name": "SuperGrok",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://x.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0026",
      "kind": "plan",
      "vendor": "xAI",
      "name": "SuperGrok Plus",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://x.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0027",
      "kind": "plan",
      "vendor": "xAI",
      "name": "SuperGrok Heavy",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://x.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0028",
      "kind": "plan",
      "vendor": "Mistral",
      "name": "Mistral Vibe Free",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://mistral.ai/pricing/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0029",
      "kind": "plan",
      "vendor": "Mistral",
      "name": "Mistral Vibe Pro",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://mistral.ai/pricing/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0030",
      "kind": "plan",
      "vendor": "Mistral",
      "name": "Mistral Vibe Team",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://mistral.ai/pricing/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0031",
      "kind": "plan",
      "vendor": "Z.ai",
      "name": "GLM Coding V3 Lite",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://z.ai/subscribe"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0032",
      "kind": "plan",
      "vendor": "Z.ai",
      "name": "GLM Coding V3 Pro",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://z.ai/subscribe"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0033",
      "kind": "plan",
      "vendor": "Z.ai",
      "name": "GLM Coding V3 Max",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://z.ai/subscribe"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0034",
      "kind": "plan",
      "vendor": "Z.ai",
      "name": "GLM Coding V1 Lite（已停售）",
      "checkedAt": "2026-10-04",
      "status": "retired",
      "sourceUrls": [
        "https://docs.z.ai/devpack/transition"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0035",
      "kind": "plan",
      "vendor": "Z.ai",
      "name": "GLM Coding V1 Pro（已停售）",
      "checkedAt": "2026-10-04",
      "status": "retired",
      "sourceUrls": [
        "https://docs.z.ai/devpack/transition"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0036",
      "kind": "plan",
      "vendor": "Z.ai",
      "name": "GLM Coding V2 Lite（老用户续费）",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://docs.z.ai/devpack/notice/usage-revision"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0037",
      "kind": "plan",
      "vendor": "Z.ai",
      "name": "GLM Coding V2 Pro（老用户续费）",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://docs.z.ai/devpack/notice/usage-revision"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0038",
      "kind": "plan",
      "vendor": "Z.ai",
      "name": "GLM Coding V2 Max（老用户续费）",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://docs.z.ai/devpack/notice/usage-revision"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0039",
      "kind": "plan",
      "vendor": "OpenCode (Anomaly/SST)",
      "name": "OpenCode Zen（按量付费）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://opencode.ai/docs/zen"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0040",
      "kind": "plan",
      "vendor": "OpenCode (Anomaly/SST)",
      "name": "OpenCode Go",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://opencode.ai/docs/go/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0041",
      "kind": "plan",
      "vendor": "OpenCode (Anomaly/SST)",
      "name": "OpenCode Enterprise",
      "checkedAt": "2026-10-04",
      "status": "custom",
      "sourceUrls": [
        "https://opencode.ai/docs/enterprise"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0042",
      "kind": "plan",
      "vendor": "R4 Coder（r4.codes）",
      "name": "Starter 预付包（已下架）",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://r4.codes/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0043",
      "kind": "plan",
      "vendor": "R4 Coder（r4.codes）",
      "name": "Code Max 预付包",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://r4.codes/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0044",
      "kind": "plan",
      "vendor": "R4 Coder（r4.codes）",
      "name": "Code Lite 预付包",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://r4.codes/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0045",
      "kind": "plan",
      "vendor": "R4 Coder（r4.codes）",
      "name": "Code Pro 预付包",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://r4.codes/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0046",
      "kind": "plan",
      "vendor": "ZenMux",
      "name": "Free",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://zenmux.ai/docs/guide/subscription.html"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0047",
      "kind": "plan",
      "vendor": "ZenMux",
      "name": "Starter",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://zenmux.ai/docs/guide/subscription.html"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0048",
      "kind": "plan",
      "vendor": "ZenMux",
      "name": "Max",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://zenmux.ai/docs/guide/subscription.html"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0049",
      "kind": "plan",
      "vendor": "ZenMux",
      "name": "Ultra",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://zenmux.ai/docs/guide/subscription.html"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0050",
      "kind": "plan",
      "vendor": "ZenMux",
      "name": "按量充值（PAYG）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://zenmux.ai/docs/guide/pay-as-you-go.html"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0051",
      "kind": "plan",
      "vendor": "PackyCode/PackyAPI",
      "name": "主站按量充值（1元=1刀）",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://codex.packycode.com/pricing",
        "https://packyapi.com/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0052",
      "kind": "plan",
      "vendor": "PackyCode (Codex 站)",
      "name": "Codex 包月（已停售）",
      "checkedAt": "2026-10-04",
      "status": "retired",
      "sourceUrls": [
        "https://codex.packycode.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0053",
      "kind": "plan",
      "vendor": "AICodeMirror",
      "name": "PRO",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://www.aicodemirror.com/api/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0054",
      "kind": "plan",
      "vendor": "AICodeMirror",
      "name": "MAX",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://www.aicodemirror.com/api/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0055",
      "kind": "plan",
      "vendor": "AICodeMirror",
      "name": "ULTRA",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://www.aicodemirror.com/api/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0056",
      "kind": "plan",
      "vendor": "88code",
      "name": "FREE（已下架）",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://docs.88code.org/88code/pricing.html",
        "https://www.88code.ai/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0057",
      "kind": "plan",
      "vendor": "88code",
      "name": "PayGo（¥66 一次性 200 刀）",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://docs.88code.org/88code/pricing.html",
        "https://www.88code.ai/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0058",
      "kind": "plan",
      "vendor": "88code",
      "name": "PLUS 包月",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://docs.88code.org/88code/pricing.html",
        "https://www.88code.ai/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0059",
      "kind": "plan",
      "vendor": "88code",
      "name": "PRO 包月",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://docs.88code.org/88code/pricing.html",
        "https://www.88code.ai/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0060",
      "kind": "plan",
      "vendor": "88code",
      "name": "MAX 包月",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://docs.88code.org/88code/pricing.html",
        "https://www.88code.ai/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0061",
      "kind": "plan",
      "vendor": "88code",
      "name": "PayGo（¥666 一次性 1988 刀）",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://docs.88code.org/88code/pricing.html",
        "https://www.88code.ai/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0062",
      "kind": "plan",
      "vendor": "DuckCoding",
      "name": "按量（分组倍率制）",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://www.duckcoding.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0063",
      "kind": "plan",
      "vendor": "AIGoCode",
      "name": "Pro（4 周订阅）",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://www.aigocode.com/en",
        "https://www.aigocode.net/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0064",
      "kind": "plan",
      "vendor": "AIGoCode",
      "name": "Max（4 周订阅）",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://www.aigocode.com/en",
        "https://www.aigocode.net/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0065",
      "kind": "plan",
      "vendor": "AIGoCode",
      "name": "Ultra（4 周订阅）",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://www.aigocode.com/en",
        "https://www.aigocode.net/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0066",
      "kind": "plan",
      "vendor": "DevPass",
      "name": "三档月订阅（$29/$79/$179）",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://devpass.llmgateway.io/",
        "https://devpass.llmgateway.io/legal/terms"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0067",
      "kind": "plan",
      "vendor": "Chutes (chutes.ai)",
      "name": "Base / Plus / Pro（$3/$10/$20）",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://chutes.ai/docs/guides/starter-guide",
        "https://chutes.ai/news/community-announcement-february",
        "https://chutes.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0068",
      "kind": "plan",
      "vendor": "Command Code",
      "name": "Go",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://commandcode.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0069",
      "kind": "plan",
      "vendor": "Command Code",
      "name": "GOAT",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://commandcode.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0070",
      "kind": "plan",
      "vendor": "Command Code",
      "name": "Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://commandcode.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0071",
      "kind": "plan",
      "vendor": "Command Code",
      "name": "Max 10×",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://commandcode.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0072",
      "kind": "plan",
      "vendor": "Command Code",
      "name": "Max 20×",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://commandcode.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0073",
      "kind": "plan",
      "vendor": "Command Code",
      "name": "Provider (API)",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://commandcode.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0074",
      "kind": "plan",
      "vendor": "AWS Kiro",
      "name": "Free",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://kiro.dev/pricing/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0075",
      "kind": "plan",
      "vendor": "AWS Kiro",
      "name": "Pro",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://kiro.dev/docs/billing/subscription-portal/",
        "https://kiro.dev/pricing/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0076",
      "kind": "plan",
      "vendor": "AWS Kiro",
      "name": "Pro+",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://kiro.dev/docs/billing/subscription-portal/",
        "https://kiro.dev/pricing/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0077",
      "kind": "plan",
      "vendor": "AWS Kiro",
      "name": "Pro Max",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://kiro.dev/docs/billing/subscription-portal/",
        "https://kiro.dev/pricing/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0078",
      "kind": "plan",
      "vendor": "AWS Kiro",
      "name": "Power",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://kiro.dev/docs/billing/subscription-portal/",
        "https://kiro.dev/pricing/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0079",
      "kind": "plan",
      "vendor": "Factory (Droid)",
      "name": "Droid Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://factory.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0080",
      "kind": "plan",
      "vendor": "Factory (Droid)",
      "name": "Droid Plus",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://factory.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0081",
      "kind": "plan",
      "vendor": "Factory (Droid)",
      "name": "Droid Max",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://factory.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0082",
      "kind": "plan",
      "vendor": "讯飞星辰 MaaS",
      "name": "Astron Coding Plan 高效版",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.xfyun.cn/doc/spark/CodingPlan.html"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0083",
      "kind": "plan",
      "vendor": "讯飞星辰 MaaS",
      "name": "Astron Coding Plan 速通版",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.xfyun.cn/doc/spark/CodingPlan.html"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0084",
      "kind": "plan",
      "vendor": "阶跃星辰 StepFun",
      "name": "Step Plan Flash Mini",
      "checkedAt": "2026-10-09",
      "status": "verified",
      "sourceUrls": [
        "https://platform.stepfun.com/docs/zh/step-plan/overview"
      ],
      "ageDays": 0,
      "stale": false
    },
    {
      "id": "plan-0085",
      "kind": "plan",
      "vendor": "阶跃星辰 StepFun",
      "name": "Step Plan Flash Plus",
      "checkedAt": "2026-10-09",
      "status": "verified",
      "sourceUrls": [
        "https://platform.stepfun.com/docs/zh/step-plan/overview"
      ],
      "ageDays": 0,
      "stale": false
    },
    {
      "id": "plan-0086",
      "kind": "plan",
      "vendor": "阶跃星辰 StepFun",
      "name": "Step Plan Flash Pro",
      "checkedAt": "2026-10-09",
      "status": "verified",
      "sourceUrls": [
        "https://platform.stepfun.com/docs/zh/step-plan/overview"
      ],
      "ageDays": 0,
      "stale": false
    },
    {
      "id": "plan-0087",
      "kind": "plan",
      "vendor": "阶跃星辰 StepFun",
      "name": "Step Plan Flash Max",
      "checkedAt": "2026-10-09",
      "status": "verified",
      "sourceUrls": [
        "https://platform.stepfun.com/docs/zh/step-plan/overview"
      ],
      "ageDays": 0,
      "stale": false
    },
    {
      "id": "plan-0088",
      "kind": "plan",
      "vendor": "Canopy Wave",
      "name": "Coding Plan Pro Bundle",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://canopywave.com/codingplan"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0089",
      "kind": "plan",
      "vendor": "OpenCode (Anomaly/SST)",
      "name": "OpenCode Go Plus",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://opencode.ai/docs/go/",
        "https://opencode.ai/go"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0090",
      "kind": "plan",
      "vendor": "GitHub Copilot",
      "name": "Free",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.github.com/en/billing/concepts/product-billing/github-copilot-licenses",
        "https://docs.github.com/en/copilot/get-started/plans"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0091",
      "kind": "plan",
      "vendor": "GitHub Copilot",
      "name": "Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.github.com/en/billing/concepts/product-billing/github-copilot-licenses",
        "https://docs.github.com/en/copilot/get-started/plans",
        "https://docs.github.com/en/copilot/reference/copilot-billing/request-based-billing-legacy/what-changed-with-billing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0092",
      "kind": "plan",
      "vendor": "GitHub Copilot",
      "name": "Pro+",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.github.com/en/billing/concepts/product-billing/github-copilot-licenses",
        "https://docs.github.com/en/copilot/get-started/plans",
        "https://docs.github.com/en/copilot/reference/copilot-billing/request-based-billing-legacy/what-changed-with-billing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0093",
      "kind": "plan",
      "vendor": "GitHub Copilot",
      "name": "Max",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.github.com/en/billing/concepts/product-billing/github-copilot-licenses",
        "https://docs.github.com/en/copilot/get-started/plans"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0094",
      "kind": "plan",
      "vendor": "GitHub Copilot",
      "name": "Business",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.github.com/en/billing/concepts/product-billing/github-copilot-licenses",
        "https://docs.github.com/en/copilot/get-started/plans"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0095",
      "kind": "plan",
      "vendor": "GitHub Copilot",
      "name": "Enterprise",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.github.com/en/billing/concepts/product-billing/github-copilot-licenses",
        "https://docs.github.com/en/copilot/get-started/plans"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0096",
      "kind": "plan",
      "vendor": "Cursor",
      "name": "Hobby",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cursor.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0097",
      "kind": "plan",
      "vendor": "Cursor",
      "name": "Start（印度专属）",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://cursor.com/docs/models-and-pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0098",
      "kind": "plan",
      "vendor": "Cursor",
      "name": "Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cursor.com/docs/models-and-pricing",
        "https://cursor.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0099",
      "kind": "plan",
      "vendor": "Cursor",
      "name": "Pro Plus",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cursor.com/docs/models-and-pricing",
        "https://cursor.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0100",
      "kind": "plan",
      "vendor": "Cursor",
      "name": "Ultra",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cursor.com/docs/models-and-pricing",
        "https://cursor.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0101",
      "kind": "plan",
      "vendor": "Cursor",
      "name": "Teams（Standard 席位）",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://cursor.com/docs/models-and-pricing",
        "https://cursor.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0102",
      "kind": "plan",
      "vendor": "Cursor",
      "name": "Teams（Premium 席位）",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://cursor.com/docs/models-and-pricing",
        "https://cursor.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0103",
      "kind": "plan",
      "vendor": "Cursor",
      "name": "Enterprise",
      "checkedAt": "2026-10-04",
      "status": "custom",
      "sourceUrls": [
        "https://cursor.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0104",
      "kind": "plan",
      "vendor": "Cognition Devin Desktop（原 Windsurf）",
      "name": "Free",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://devin.ai/pricing",
        "https://docs.devin.ai/admin/billing/self-serve"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0105",
      "kind": "plan",
      "vendor": "Cognition Devin Desktop（原 Windsurf）",
      "name": "Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://devin.ai/pricing",
        "https://docs.devin.ai/admin/billing/self-serve",
        "https://docs.devin.ai/desktop/accounts/quota"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0106",
      "kind": "plan",
      "vendor": "Cognition Devin Desktop（原 Windsurf）",
      "name": "Max",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://devin.ai/pricing",
        "https://docs.devin.ai/admin/billing/self-serve"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0107",
      "kind": "plan",
      "vendor": "Cognition Devin Desktop（原 Windsurf）",
      "name": "Teams（full seat）",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://devin.ai/pricing",
        "https://docs.devin.ai/admin/billing/self-serve"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0108",
      "kind": "plan",
      "vendor": "Cognition Devin（云 agent）",
      "name": "Free",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://devin.ai/pricing",
        "https://docs.devin.ai/admin/billing/self-serve"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0109",
      "kind": "plan",
      "vendor": "Cognition Devin（云 agent）",
      "name": "Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://devin.ai/pricing",
        "https://docs.devin.ai/admin/billing/self-serve"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0110",
      "kind": "plan",
      "vendor": "Cognition Devin（云 agent）",
      "name": "Max",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://devin.ai/pricing",
        "https://docs.devin.ai/admin/billing/self-serve"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0111",
      "kind": "plan",
      "vendor": "Cognition Devin（云 agent）",
      "name": "Enterprise",
      "checkedAt": "2026-10-04",
      "status": "custom",
      "sourceUrls": [
        "https://devin.ai/pricing",
        "https://docs.devin.ai/admin/billing/enterprise"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0112",
      "kind": "plan",
      "vendor": "Zed",
      "name": "Free",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://zed.dev/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0113",
      "kind": "plan",
      "vendor": "Zed",
      "name": "Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://zed.dev/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0114",
      "kind": "plan",
      "vendor": "Zed",
      "name": "Business",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://zed.dev/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0115",
      "kind": "plan",
      "vendor": "Augment Code",
      "name": "Business",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.augmentcode.com/models/token-based-pricing",
        "https://www.augmentcode.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0116",
      "kind": "plan",
      "vendor": "Augment Code",
      "name": "Enterprise",
      "checkedAt": "2026-10-04",
      "status": "custom",
      "sourceUrls": [
        "https://www.augmentcode.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0117",
      "kind": "plan",
      "vendor": "Cline",
      "name": "开源版 + 按量充值",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.cline.bot/getting-started/cline-provider",
        "https://github.com/cline/cline"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0118",
      "kind": "plan",
      "vendor": "Cline",
      "name": "ClinePass",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.cline.bot/getting-started/clinepass"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0119",
      "kind": "plan",
      "vendor": "Roo Code",
      "name": "开源版（已下架）",
      "checkedAt": "2026-10-04",
      "status": "retired",
      "sourceUrls": [
        "https://github.com/RooCodeInc/Roo-Code"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0120",
      "kind": "plan",
      "vendor": "Roo Code（Roomote）",
      "name": "自托管（≤10 用户）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://roomote.dev/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0121",
      "kind": "plan",
      "vendor": "Roo Code（Roomote）",
      "name": "Roomote ≤10 users",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://roomote.dev/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0122",
      "kind": "plan",
      "vendor": "Roo Code（Roomote）",
      "name": "Roomote 11–50 users",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://roomote.dev/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0123",
      "kind": "plan",
      "vendor": "Roo Code（Roomote）",
      "name": "Roomote 51–100 users",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://roomote.dev/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0124",
      "kind": "plan",
      "vendor": "Kilo Code",
      "name": "Free（BYOK/零加价）",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://kilo.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0125",
      "kind": "plan",
      "vendor": "Kilo Code",
      "name": "Teams",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://kilo.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0126",
      "kind": "plan",
      "vendor": "Sourcegraph Amp",
      "name": "Hobby",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://ampcode.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0127",
      "kind": "plan",
      "vendor": "Sourcegraph Amp",
      "name": "Individual（Megawatt）",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://ampcode.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0128",
      "kind": "plan",
      "vendor": "JetBrains AI",
      "name": "AI Pro（个人）",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://www.jetbrains.com/ai-ides/buy/",
        "https://www.jetbrains.com/help/ai-assistant/licensing-and-subscriptions.html"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0129",
      "kind": "plan",
      "vendor": "JetBrains AI",
      "name": "AI Ultimate（个人）",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://www.jetbrains.com/ai-ides/buy/",
        "https://www.jetbrains.com/help/ai-assistant/licensing-and-subscriptions.html"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0130",
      "kind": "plan",
      "vendor": "JetBrains AI",
      "name": "AI Pro（商业）",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://www.jetbrains.com/ai-ides/buy/",
        "https://www.jetbrains.com/help/ai-assistant/licensing-and-subscriptions.html"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0131",
      "kind": "plan",
      "vendor": "JetBrains AI",
      "name": "AI Ultimate（商业）",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://www.jetbrains.com/ai-ides/buy/",
        "https://www.jetbrains.com/help/ai-assistant/licensing-and-subscriptions.html"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0132",
      "kind": "plan",
      "vendor": "OpenRouter",
      "name": "Free",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://openrouter.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0133",
      "kind": "plan",
      "vendor": "Lovable",
      "name": "Free",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.lovable.dev/introduction/subscription-plans"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0134",
      "kind": "plan",
      "vendor": "Lovable",
      "name": "Pro（100 credits）",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://docs.lovable.dev/introduction/subscription-plans"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0135",
      "kind": "plan",
      "vendor": "Lovable",
      "name": "Business（100 credits）",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://docs.lovable.dev/introduction/subscription-plans"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0136",
      "kind": "plan",
      "vendor": "Lovable",
      "name": "Enterprise",
      "checkedAt": "2026-10-04",
      "status": "custom",
      "sourceUrls": [
        "https://docs.lovable.dev/introduction/subscription-plans"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0137",
      "kind": "plan",
      "vendor": "Bolt.new",
      "name": "Free",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://bolt.new/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0138",
      "kind": "plan",
      "vendor": "Bolt.new",
      "name": "Pro",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://bolt.new/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0139",
      "kind": "plan",
      "vendor": "Bolt.new",
      "name": "Teams",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://bolt.new/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0140",
      "kind": "plan",
      "vendor": "Bolt.new",
      "name": "Enterprise",
      "checkedAt": "2026-10-04",
      "status": "custom",
      "sourceUrls": [
        "https://bolt.new/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0141",
      "kind": "plan",
      "vendor": "Replit",
      "name": "Core",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://replit.com/blog/pro-plan",
        "https://replit.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0142",
      "kind": "plan",
      "vendor": "Replit",
      "name": "Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://replit.com/blog/pro-plan",
        "https://replit.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0143",
      "kind": "plan",
      "vendor": "Replit",
      "name": "Enterprise",
      "checkedAt": "2026-10-04",
      "status": "custom",
      "sourceUrls": [
        "https://replit.com/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0144",
      "kind": "plan",
      "vendor": "AWS",
      "name": "Amazon Q Developer Free",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://aws.amazon.com/q/developer/pricing/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0145",
      "kind": "plan",
      "vendor": "AWS",
      "name": "Amazon Q Developer Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://aws.amazon.com/q/developer/pricing/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0146",
      "kind": "plan",
      "vendor": "阿里云 Qoder CN（原通义灵码）",
      "name": "团队版",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://qoder.com.cn/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0147",
      "kind": "plan",
      "vendor": "阿里云 Qoder CN（原通义灵码）",
      "name": "企业标准版",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://qoder.com.cn/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0148",
      "kind": "plan",
      "vendor": "阿里云 Qoder CN（原通义灵码）",
      "name": "企业专属版",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://qoder.com.cn/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0149",
      "kind": "plan",
      "vendor": "腾讯云 CodeBuddy",
      "name": "企业旗舰版",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://www.codebuddy.cn/pricing/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0150",
      "kind": "plan",
      "vendor": "华为云",
      "name": "CodeArts 代码智能体（原 CodeArts Snap）",
      "checkedAt": "2026-10-04",
      "status": "unverified",
      "sourceUrls": [
        "https://www.huaweicloud.com/product/codearts.html"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0151",
      "kind": "plan",
      "vendor": "智谱 BigModel",
      "name": "GLM Coding V1 Lite（已停售）",
      "checkedAt": "2026-10-04",
      "status": "retired",
      "sourceUrls": [
        "https://docs.bigmodel.cn/cn/coding-plan/notice/usage-revision"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0152",
      "kind": "plan",
      "vendor": "智谱 BigModel",
      "name": "GLM Coding V1 Pro（已停售）",
      "checkedAt": "2026-10-04",
      "status": "retired",
      "sourceUrls": [
        "https://docs.bigmodel.cn/cn/coding-plan/notice/usage-revision"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0153",
      "kind": "plan",
      "vendor": "智谱 BigModel",
      "name": "GLM Coding V1 Max（已停售）",
      "checkedAt": "2026-10-04",
      "status": "retired",
      "sourceUrls": [
        "https://docs.bigmodel.cn/cn/coding-plan/notice/usage-revision"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0154",
      "kind": "plan",
      "vendor": "智谱 BigModel",
      "name": "GLM Coding V2 Lite（老用户续费）",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://docs.bigmodel.cn/cn/coding-plan/notice/usage-revision"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0155",
      "kind": "plan",
      "vendor": "智谱 BigModel",
      "name": "GLM Coding V2 Pro（老用户续费）",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://docs.bigmodel.cn/cn/coding-plan/notice/usage-revision"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0156",
      "kind": "plan",
      "vendor": "智谱 BigModel",
      "name": "GLM Coding V2 Max（老用户续费）",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://docs.bigmodel.cn/cn/coding-plan/notice/usage-revision"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0157",
      "kind": "plan",
      "vendor": "智谱 BigModel",
      "name": "GLM Coding V3 Lite",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://bigmodel.cn/glm-coding"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0158",
      "kind": "plan",
      "vendor": "智谱 BigModel",
      "name": "GLM Coding V3 Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://bigmodel.cn/glm-coding"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0159",
      "kind": "plan",
      "vendor": "智谱 BigModel",
      "name": "GLM Coding V3 Max",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://bigmodel.cn/glm-coding"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0160",
      "kind": "plan",
      "vendor": "智谱 BigModel",
      "name": "GLM Coding Plan 团队标准版",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://bigmodel.cn/glm-coding"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0161",
      "kind": "plan",
      "vendor": "月之暗面 Kimi",
      "name": "Kimi Code Plan Plus",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.kimi.com/membership/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0162",
      "kind": "plan",
      "vendor": "月之暗面 Kimi",
      "name": "Kimi Code Plan Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.kimi.com/membership/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0163",
      "kind": "plan",
      "vendor": "月之暗面 Kimi",
      "name": "Kimi Code Plan Max",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.kimi.com/membership/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0164",
      "kind": "plan",
      "vendor": "MiniMax",
      "name": "Token Plan Plus",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://platform.minimax.cn/docs/guides/pricing-token-plan"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0165",
      "kind": "plan",
      "vendor": "MiniMax",
      "name": "Token Plan Max",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://platform.minimax.cn/docs/guides/pricing-token-plan"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0166",
      "kind": "plan",
      "vendor": "MiniMax",
      "name": "Token Plan Ultra",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://platform.minimax.cn/docs/guides/pricing-token-plan"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0167",
      "kind": "plan",
      "vendor": "小米 MiMo",
      "name": "Token Plan Lite",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://mimo.mi.com/docs/zh-CN/price/token-plan"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0168",
      "kind": "plan",
      "vendor": "小米 MiMo",
      "name": "Token Plan Standard",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://mimo.mi.com/docs/zh-CN/price/token-plan"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0169",
      "kind": "plan",
      "vendor": "小米 MiMo",
      "name": "Token Plan Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://mimo.mi.com/docs/zh-CN/price/token-plan"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0170",
      "kind": "plan",
      "vendor": "小米 MiMo",
      "name": "Token Plan Max",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://mimo.mi.com/docs/zh-CN/price/token-plan"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0171",
      "kind": "plan",
      "vendor": "小米 MiMo",
      "name": "Token Plan 团队 Standard",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://mimo.mi.com/docs/zh-CN/price/token-plan"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0172",
      "kind": "plan",
      "vendor": "小米 MiMo",
      "name": "Token Plan 团队 Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://mimo.mi.com/docs/zh-CN/price/token-plan"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0173",
      "kind": "plan",
      "vendor": "小米 MiMo",
      "name": "Token Plan 团队 Max",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://mimo.mi.com/docs/zh-CN/price/token-plan"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0174",
      "kind": "plan",
      "vendor": "腾讯云 TokenHub",
      "name": "通用 Token Plan Lite",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cloud.tencent.com/document/product/1823/130060"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0175",
      "kind": "plan",
      "vendor": "腾讯云 TokenHub",
      "name": "通用 Token Plan Standard",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cloud.tencent.com/document/product/1823/130060"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0176",
      "kind": "plan",
      "vendor": "腾讯云 TokenHub",
      "name": "通用 Token Plan Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cloud.tencent.com/document/product/1823/130060"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0177",
      "kind": "plan",
      "vendor": "腾讯云 TokenHub",
      "name": "通用 Token Plan Max",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cloud.tencent.com/document/product/1823/130060"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0178",
      "kind": "plan",
      "vendor": "百度千帆",
      "name": "Token Plan Mini",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cloud.baidu.com/product/qianfan_home/token_plan_personal.html"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0179",
      "kind": "plan",
      "vendor": "百度千帆",
      "name": "Token Plan Lite",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cloud.baidu.com/product/qianfan_home/token_plan_personal.html"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0180",
      "kind": "plan",
      "vendor": "百度千帆",
      "name": "Token Plan Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cloud.baidu.com/product/qianfan_home/token_plan_personal.html"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0181",
      "kind": "plan",
      "vendor": "百度千帆",
      "name": "Token Plan Max",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cloud.baidu.com/product/qianfan_home/token_plan_personal.html"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0182",
      "kind": "plan",
      "vendor": "七牛云",
      "name": "企业 Token Plan S",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.qiniu.com/ai/plan"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0183",
      "kind": "plan",
      "vendor": "七牛云",
      "name": "企业 Token Plan M",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.qiniu.com/ai/plan"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0184",
      "kind": "plan",
      "vendor": "七牛云",
      "name": "企业 Token Plan B",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.qiniu.com/ai/plan"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0185",
      "kind": "plan",
      "vendor": "阿里云 Qoder CN（原通义灵码）",
      "name": "个人体验版（Free）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://qoder.com.cn/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0186",
      "kind": "plan",
      "vendor": "阿里云 Qoder CN（原通义灵码）",
      "name": "个人专业版（Pro）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://qoder.com.cn/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0187",
      "kind": "plan",
      "vendor": "阿里云 Qoder CN（原通义灵码）",
      "name": "个人高级版（Pro+）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://qoder.com.cn/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0188",
      "kind": "plan",
      "vendor": "腾讯云 CodeBuddy",
      "name": "体验版（个人免费）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.codebuddy.cn/pricing/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0189",
      "kind": "plan",
      "vendor": "腾讯云 CodeBuddy",
      "name": "标准版（个人）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.codebuddy.cn/pricing/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0190",
      "kind": "plan",
      "vendor": "腾讯云 CodeBuddy",
      "name": "高级版（个人）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.codebuddy.cn/pricing/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0191",
      "kind": "plan",
      "vendor": "腾讯云 CodeBuddy",
      "name": "旗舰版（个人）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.codebuddy.cn/pricing/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0192",
      "kind": "plan",
      "vendor": "字节跳动 Trae（国内版）",
      "name": "Trae Free",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.trae.cn/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0193",
      "kind": "plan",
      "vendor": "字节跳动 Trae（国内版）",
      "name": "会员 Lite",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.trae.cn/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0194",
      "kind": "plan",
      "vendor": "字节跳动 Trae（国内版）",
      "name": "会员 Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.trae.cn/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0195",
      "kind": "plan",
      "vendor": "字节跳动 Trae（国内版）",
      "name": "会员 Pro+",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.trae.cn/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0196",
      "kind": "plan",
      "vendor": "字节跳动 Trae（国内版）",
      "name": "会员 Ultra",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.trae.cn/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0197",
      "kind": "plan",
      "vendor": "字节跳动 Trae（国际版）",
      "name": "Trae Pro",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://www.trae.ai/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0198",
      "kind": "plan",
      "vendor": "百度 DuMate",
      "name": "免费版",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.dumate.cn/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0199",
      "kind": "plan",
      "vendor": "百度 DuMate",
      "name": "Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.dumate.cn/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0200",
      "kind": "plan",
      "vendor": "百度 DuMate",
      "name": "Max",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://www.dumate.cn/"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0201",
      "kind": "plan",
      "vendor": "百度文心快码 Comate",
      "name": "个人标准版",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://comate.baidu.com/zh/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0202",
      "kind": "plan",
      "vendor": "腾讯云（LKEAP 知识引擎）",
      "name": "腾讯云 Coding Plan Lite",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cloud.tencent.com/document/product/1823/130092"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0203",
      "kind": "plan",
      "vendor": "腾讯云（LKEAP 知识引擎）",
      "name": "腾讯云 Coding Plan Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cloud.tencent.com/document/product/1823/130092"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0204",
      "kind": "plan",
      "vendor": "阿里云百炼",
      "name": "Token Plan 个人版 Lite",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://help.aliyun.com/zh/model-studio/token-plan-overview"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0205",
      "kind": "plan",
      "vendor": "阿里云百炼",
      "name": "Token Plan 个人版 Essential",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://help.aliyun.com/zh/model-studio/token-plan-overview"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0206",
      "kind": "plan",
      "vendor": "阿里云百炼",
      "name": "Token Plan 个人版 Standard",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://help.aliyun.com/zh/model-studio/token-plan-overview"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0207",
      "kind": "plan",
      "vendor": "阿里云百炼",
      "name": "Token Plan 个人版 Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://help.aliyun.com/zh/model-studio/token-plan-overview"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0208",
      "kind": "plan",
      "vendor": "阿里云百炼",
      "name": "Token Plan 团队版（标准座席）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://help.aliyun.com/zh/model-studio/token-plan-overview"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0209",
      "kind": "plan",
      "vendor": "阿里云百炼",
      "name": "Coding Plan Pro（限量抢购）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://help.aliyun.com/zh/model-studio/coding-plan",
        "https://help.aliyun.com/zh/model-studio/token-plan-overview"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0210",
      "kind": "plan",
      "vendor": "火山引擎方舟（字节）",
      "name": "方舟 Coding Plan Lite",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.volcengine.com/docs/ark/coding-plan-personal-universal-promotion?lang=zh",
        "https://docs.volcengine.com/docs/ark/model-pricing?lang=zh"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0211",
      "kind": "plan",
      "vendor": "火山引擎方舟（字节）",
      "name": "方舟 Coding Plan Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.volcengine.com/docs/ark/coding-plan-personal-universal-promotion?lang=zh",
        "https://docs.volcengine.com/docs/ark/model-pricing?lang=zh"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "plan-0212",
      "kind": "plan",
      "vendor": "火山引擎方舟（字节）",
      "name": "方舟 Agent Plan（Small）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.volcengine.com/docs/ark/agent-plan-personal-plan-overview?lang=zh",
        "https://docs.volcengine.com/docs/ark/model-pricing?lang=zh"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "Anthropic|Claude Sonnet 5.5",
      "kind": "api",
      "vendor": "Anthropic",
      "name": "Claude Sonnet 5.5",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://platform.claude.com/docs/en/about-claude/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "Anthropic|Claude Sonnet 5",
      "kind": "api",
      "vendor": "Anthropic",
      "name": "Claude Sonnet 5",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://platform.claude.com/docs/en/about-claude/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "Anthropic|Claude Opus 5.5",
      "kind": "api",
      "vendor": "Anthropic",
      "name": "Claude Opus 5.5",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://platform.claude.com/docs/en/about-claude/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "OpenAI|gpt-6-astra",
      "kind": "api",
      "vendor": "OpenAI",
      "name": "gpt-6-astra",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://developers.openai.com/api/docs/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "OpenAI|gpt-6.1-sol",
      "kind": "api",
      "vendor": "OpenAI",
      "name": "gpt-6.1-sol",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://developers.openai.com/api/docs/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "OpenAI|gpt-6-sol",
      "kind": "api",
      "vendor": "OpenAI",
      "name": "gpt-6-sol",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://developers.openai.com/api/docs/models/gpt-6-sol"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "OpenAI|gpt-6-luna",
      "kind": "api",
      "vendor": "OpenAI",
      "name": "gpt-6-luna",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://developers.openai.com/api/docs/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "OpenAI|gpt-5.6-sol",
      "kind": "api",
      "vendor": "OpenAI",
      "name": "gpt-5.6-sol",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://developers.openai.com/api/docs/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "OpenAI|gpt-5.6-terra",
      "kind": "api",
      "vendor": "OpenAI",
      "name": "gpt-5.6-terra",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://developers.openai.com/api/docs/models/gpt-5.6-terra"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "OpenAI|gpt-5.6-luna",
      "kind": "api",
      "vendor": "OpenAI",
      "name": "gpt-5.6-luna",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://developers.openai.com/api/docs/models/gpt-5.6-luna"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "OpenAI|gpt-5.3-codex（编程向）",
      "kind": "api",
      "vendor": "OpenAI",
      "name": "gpt-5.3-codex（编程向）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://developers.openai.com/api/docs/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "Google|Gemini 3.1 Pro Preview",
      "kind": "api",
      "vendor": "Google",
      "name": "Gemini 3.1 Pro Preview",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://ai.google.dev/gemini-api/docs/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "Z.ai|GLM-5.3",
      "kind": "api",
      "vendor": "Z.ai",
      "name": "GLM-5.3",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.z.ai/guides/overview/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "DeepSeek|deepseek-flash (V4.1-Flash)",
      "kind": "api",
      "vendor": "DeepSeek",
      "name": "deepseek-flash (V4.1-Flash)",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://api-docs.deepseek.com/quick_start/pricing/?helper=penn&method=individual"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "DeepSeek|deepseek-v4-pro (V4-Pro-0813)",
      "kind": "api",
      "vendor": "DeepSeek",
      "name": "deepseek-v4-pro (V4-Pro-0813)",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://api-docs.deepseek.com/quick_start/pricing/?helper=penn&method=individual"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "智谱 BigModel|GLM-5.3",
      "kind": "api",
      "vendor": "智谱 BigModel",
      "name": "GLM-5.3",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.bigmodel.cn/cn/guide/start/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "月之暗面 Kimi|Kimi K3（kimi-k3）",
      "kind": "api",
      "vendor": "月之暗面 Kimi",
      "name": "Kimi K3（kimi-k3）",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://platform.kimi.com/docs/pricing/chat"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "月之暗面 Kimi|Kimi K2.7-Code",
      "kind": "api",
      "vendor": "月之暗面 Kimi",
      "name": "Kimi K2.7-Code",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://platform.kimi.com/docs/pricing/chat"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "MiniMax|MiniMax-M3",
      "kind": "api",
      "vendor": "MiniMax",
      "name": "MiniMax-M3",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://platform.minimax.cn/docs/guides/pricing-paygo"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "MiniMax|MiniMax-M2.7",
      "kind": "api",
      "vendor": "MiniMax",
      "name": "MiniMax-M2.7",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://platform.minimax.cn/docs/guides/pricing-paygo"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "阿里云百炼|qwen3-coder-next",
      "kind": "api",
      "vendor": "阿里云百炼",
      "name": "qwen3-coder-next",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://help.aliyun.com/zh/model-studio/qwen3-coder-next"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "阿里云百炼|qwen3-coder-plus",
      "kind": "api",
      "vendor": "阿里云百炼",
      "name": "qwen3-coder-plus",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://help.aliyun.com/zh/model-studio/qwen3-coder-plus"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "阿里云百炼|qwen3-coder-flash",
      "kind": "api",
      "vendor": "阿里云百炼",
      "name": "qwen3-coder-flash",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://help.aliyun.com/zh/model-studio/qwen3-coder-flash"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "火山引擎（豆包/方舟）|doubao-seed-2.0-code",
      "kind": "api",
      "vendor": "火山引擎（豆包/方舟）",
      "name": "doubao-seed-2.0-code",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.volcengine.com/docs/ark/model-pricing?lang=zh"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "火山引擎（豆包/方舟）|doubao-seed-2.1-pro",
      "kind": "api",
      "vendor": "火山引擎（豆包/方舟）",
      "name": "doubao-seed-2.1-pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.volcengine.com/docs/ark/model-pricing?lang=zh"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "阶跃星辰 StepFun|step-5-preview",
      "kind": "api",
      "vendor": "阶跃星辰 StepFun",
      "name": "step-5-preview",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://platform.stepfun.com/docs/zh/guides/pricing/details"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "阶跃星辰 StepFun|step-3.7-flash",
      "kind": "api",
      "vendor": "阶跃星辰 StepFun",
      "name": "step-3.7-flash",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://platform.stepfun.com/docs/zh/guides/pricing/details"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "硅基流动 SiliconFlow|zai-org/GLM-5.3",
      "kind": "api",
      "vendor": "硅基流动 SiliconFlow",
      "name": "zai-org/GLM-5.3",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://cloud-rd.siliconflow.cn/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "硅基流动 SiliconFlow|moonshotai/Kimi-K2.7-Code",
      "kind": "api",
      "vendor": "硅基流动 SiliconFlow",
      "name": "moonshotai/Kimi-K2.7-Code",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cloud-rd.siliconflow.cn/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "硅基流动 SiliconFlow|deepseek-ai/DeepSeek-V4-Pro",
      "kind": "api",
      "vendor": "硅基流动 SiliconFlow",
      "name": "deepseek-ai/DeepSeek-V4-Pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cloud-rd.siliconflow.cn/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "硅基流动 SiliconFlow|Qwen/Qwen3.8-27B",
      "kind": "api",
      "vendor": "硅基流动 SiliconFlow",
      "name": "Qwen/Qwen3.8-27B",
      "checkedAt": "2026-10-04",
      "status": "changed",
      "sourceUrls": [
        "https://cloud-rd.siliconflow.cn/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "阿里云百炼|qwen3.8-flash",
      "kind": "api",
      "vendor": "阿里云百炼",
      "name": "qwen3.8-flash",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://help.aliyun.com/zh/model-studio/qwen3-8-flash"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "腾讯云 TokenHub|hy3",
      "kind": "api",
      "vendor": "腾讯云 TokenHub",
      "name": "hy3",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cloud.tencent.com/document/product/1823/130055"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "腾讯云 TokenHub|hy4-preview",
      "kind": "api",
      "vendor": "腾讯云 TokenHub",
      "name": "hy4-preview",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://cloud.tencent.com/document/product/1823/130055"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "小米 MiMo|mimo-v2.6-flash",
      "kind": "api",
      "vendor": "小米 MiMo",
      "name": "mimo-v2.6-flash",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://mimo.mi.com/docs/zh-CN/price/pay-as-you-go"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "小米 MiMo|mimo-v2.6-pro",
      "kind": "api",
      "vendor": "小米 MiMo",
      "name": "mimo-v2.6-pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://mimo.mi.com/docs/zh-CN/price/pay-as-you-go"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "DeepSeek|deepseek-flash",
      "kind": "payg",
      "vendor": "DeepSeek",
      "name": "deepseek-flash",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://api-docs.deepseek.com/quick_start/pricing/?helper=penn&method=individual"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "DeepSeek|deepseek-v4-pro",
      "kind": "payg",
      "vendor": "DeepSeek",
      "name": "deepseek-v4-pro",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://api-docs.deepseek.com/quick_start/pricing/?helper=penn&method=individual"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "Z.ai|GLM-5.3",
      "kind": "payg",
      "vendor": "Z.ai",
      "name": "GLM-5.3",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.z.ai/guides/overview/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "Z.ai|GLM-5.3-Flash",
      "kind": "payg",
      "vendor": "Z.ai",
      "name": "GLM-5.3-Flash",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.z.ai/guides/overview/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "智谱 BigModel|GLM-5.3",
      "kind": "payg",
      "vendor": "智谱 BigModel",
      "name": "GLM-5.3",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.bigmodel.cn/cn/guide/start/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "智谱 BigModel|GLM-5.3-Flash",
      "kind": "payg",
      "vendor": "智谱 BigModel",
      "name": "GLM-5.3-Flash",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://docs.bigmodel.cn/cn/guide/start/pricing"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "月之暗面 Kimi|Kimi K3",
      "kind": "payg",
      "vendor": "月之暗面 Kimi",
      "name": "Kimi K3",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://platform.kimi.com/docs/pricing/chat"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "月之暗面 Kimi|Kimi K2.7-Code",
      "kind": "payg",
      "vendor": "月之暗面 Kimi",
      "name": "Kimi K2.7-Code",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://platform.kimi.com/docs/pricing/chat"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "MiniMax|MiniMax-M3",
      "kind": "payg",
      "vendor": "MiniMax",
      "name": "MiniMax-M3",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://platform.minimax.cn/docs/guides/pricing-paygo"
      ],
      "ageDays": 5,
      "stale": false
    },
    {
      "id": "阿里云百炼|qwen3-coder-plus",
      "kind": "payg",
      "vendor": "阿里云百炼",
      "name": "qwen3-coder-plus",
      "checkedAt": "2026-10-04",
      "status": "verified",
      "sourceUrls": [
        "https://help.aliyun.com/zh/model-studio/qwen3-coder-plus"
      ],
      "ageDays": 5,
      "stale": false
    }
  ],
  "reviews": [
    {
      "id": "glm-holiday-20261007",
      "title": "复核智谱 / Z.ai 双节与夜间活动结束后的权益",
      "planIds": [
        "plan-0031",
        "plan-0032",
        "plan-0033",
        "plan-0157",
        "plan-0158",
        "plan-0159"
      ],
      "reviewOn": "2026-10-08",
      "source": "https://docs.bigmodel.cn/cn/coding-plan/overview.md",
      "note": "原公告活动截至 10-07；这是复核提醒，不代表已确认新的消耗规则。",
      "daysUntil": -1,
      "overdue": true,
      "due": true
    },
    {
      "id": "openai-gpt55-20261014",
      "title": "复核 GPT-5.5 退役与套餐可用模型",
      "vendor": "OpenAI",
      "reviewOn": "2026-10-14",
      "source": "https://learn.chatgpt.com/docs/pricing",
      "note": "按已记录公告安排复核，官网核实后再修改模型与权益。",
      "planIds": [
        "plan-0008",
        "plan-0009",
        "plan-0010",
        "plan-0011",
        "plan-0012",
        "plan-0013",
        "plan-0014",
        "plan-0015"
      ],
      "daysUntil": 5,
      "overdue": false,
      "due": false
    },
    {
      "id": "volc-promotion-20261108",
      "title": "复核方舟 Coding Plan 两个月优惠活动",
      "planIds": [
        "plan-0210",
        "plan-0211"
      ],
      "reviewOn": "2026-11-09",
      "source": "https://docs.volcengine.com/docs/ark/coding-plan-personal-universal-promotion?lang=zh",
      "note": "原活动截至 11-08；常规续费价与个人资格需重新检查。",
      "daysUntil": 31,
      "overdue": false,
      "due": false
    },
    {
      "id": "sol-promotion-20261121",
      "title": "复核 GPT-5.6 Sol credits 促销是否延续",
      "vendor": "OpenAI",
      "reviewOn": "2026-11-22",
      "source": "https://learn.chatgpt.com/docs/pricing",
      "note": "原公告为至少延续至 11-21，不能推断次日一定涨价。",
      "planIds": [
        "plan-0008",
        "plan-0009",
        "plan-0010",
        "plan-0011",
        "plan-0012",
        "plan-0013",
        "plan-0014",
        "plan-0015"
      ],
      "daysUntil": 44,
      "overdue": false,
      "due": false
    },
    {
      "id": "gemini-intro-20261231",
      "title": "复核 Gemini Flash 介绍价与生效时间",
      "vendor": "Google",
      "reviewOn": "2027-01-01",
      "source": "https://ai.google.dev/gemini-api/docs/pricing",
      "note": "按库内记录的介绍价截止日安排复核；发布新价格前需重新核实。",
      "planIds": [
        "plan-0016",
        "plan-0017",
        "plan-0018",
        "plan-0019",
        "plan-0020",
        "plan-0021",
        "plan-0022"
      ],
      "daysUntil": 84,
      "overdue": false,
      "due": false
    }
  ],
  "changes": [
    {
      "changeId": "change-0029c9700fd6b55344765dec",
      "id": "硅基流动 SiliconFlow|zai-org/GLM-5.3",
      "kind": "api",
      "vendor": "硅基流动 SiliconFlow",
      "name": "zai-org/GLM-5.3",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://cloud-rd.siliconflow.cn/pricing"
      ],
      "fields": [
        "inCNY"
      ],
      "before": {
        "inCNY": 6
      },
      "after": {
        "inCNY": 8
      },
      "model": "zai-org/GLM-5.3"
    },
    {
      "changeId": "change-1ddd2f26b385ca4cce5c0889",
      "id": "plan-0135",
      "kind": "plan",
      "vendor": "Lovable",
      "name": "Business（100 credits）",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://docs.lovable.dev/introduction/subscription-plans"
      ],
      "fields": [
        "priceY"
      ],
      "before": {
        "priceY": 42
      },
      "after": {
        "priceY": 41.67
      },
      "plan": "Business（100 credits）"
    },
    {
      "changeId": "change-255d9ace38e030ac418c588e",
      "id": "plan-0101",
      "kind": "plan",
      "vendor": "Cursor",
      "name": "Teams（Standard 席位）",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://cursor.com/docs/models-and-pricing",
        "https://cursor.com/pricing"
      ],
      "fields": [
        "priceY"
      ],
      "before": {
        "priceY": null
      },
      "after": {
        "priceY": 32
      },
      "plan": "Teams（Standard 席位）"
    },
    {
      "changeId": "change-3182b6de09f4ddd7c58e06f0",
      "id": "plan-0033",
      "kind": "plan",
      "vendor": "Z.ai",
      "name": "GLM Coding V3 Max",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://z.ai/subscribe"
      ],
      "fields": [
        "priceM",
        "priceY"
      ],
      "before": {
        "priceM": 160,
        "priceY": 128
      },
      "after": {
        "priceM": 168,
        "priceY": 117.6
      },
      "plan": "GLM Coding V3 Max"
    },
    {
      "changeId": "change-3f6953b4667c1dd71f3a9ec6",
      "id": "plan-0134",
      "kind": "plan",
      "vendor": "Lovable",
      "name": "Pro（100 credits）",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://docs.lovable.dev/introduction/subscription-plans"
      ],
      "fields": [
        "priceY"
      ],
      "before": {
        "priceY": 21
      },
      "after": {
        "priceY": 20.83
      },
      "plan": "Pro（100 credits）"
    },
    {
      "changeId": "change-480f09d4107d62f910374368",
      "id": "plan-0026",
      "kind": "plan",
      "vendor": "xAI",
      "name": "SuperGrok Plus",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://x.ai/pricing"
      ],
      "fields": [
        "priceY"
      ],
      "before": {
        "priceY": 83.33
      },
      "after": {
        "priceY": null
      },
      "plan": "SuperGrok Plus"
    },
    {
      "changeId": "change-503b4179a50e7cf33d46eab1",
      "id": "plan-0197",
      "kind": "plan",
      "vendor": "字节跳动 Trae（国际版）",
      "name": "Trae Pro",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://www.trae.ai/pricing"
      ],
      "fields": [
        "priceY"
      ],
      "before": {
        "priceY": null
      },
      "after": {
        "priceY": 7.5
      },
      "plan": "Trae Pro"
    },
    {
      "changeId": "change-5dd6fd47e0331163af1b6c6e",
      "id": "plan-0102",
      "kind": "plan",
      "vendor": "Cursor",
      "name": "Teams（Premium 席位）",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://cursor.com/docs/models-and-pricing",
        "https://cursor.com/pricing"
      ],
      "fields": [
        "priceY"
      ],
      "before": {
        "priceY": null
      },
      "after": {
        "priceY": 96
      },
      "plan": "Teams（Premium 席位）"
    },
    {
      "changeId": "change-5e5a0320dc4615f448119a35",
      "id": "plan-0017",
      "kind": "plan",
      "vendor": "Google",
      "name": "Google AI Pro",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://one.google.com/about/google-ai-plans/"
      ],
      "fields": [
        "priceY"
      ],
      "before": {
        "priceY": null
      },
      "after": {
        "priceY": 16.67
      },
      "plan": "Google AI Pro"
    },
    {
      "changeId": "change-67a89830e048c3cc060aa4b8",
      "id": "plan-0139",
      "kind": "plan",
      "vendor": "Bolt.new",
      "name": "Teams",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://bolt.new/pricing"
      ],
      "fields": [
        "priceY"
      ],
      "before": {
        "priceY": null
      },
      "after": {
        "priceY": 27
      },
      "plan": "Teams"
    },
    {
      "changeId": "change-717c2777ffebf7b15a65edc9",
      "id": "plan-0154",
      "kind": "plan",
      "vendor": "智谱 BigModel",
      "name": "GLM Coding V2 Lite（老用户续费）",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://docs.bigmodel.cn/cn/coding-plan/notice/usage-revision"
      ],
      "fields": [
        "priceY"
      ],
      "before": {
        "priceY": null
      },
      "after": {
        "priceY": 39.2
      },
      "plan": "GLM Coding V2 Lite（老用户续费）"
    },
    {
      "changeId": "change-72dda49670b16f04542dc0e8",
      "id": "plan-0025",
      "kind": "plan",
      "vendor": "xAI",
      "name": "SuperGrok",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://x.ai/pricing"
      ],
      "fields": [
        "priceY"
      ],
      "before": {
        "priceY": 25
      },
      "after": {
        "priceY": null
      },
      "plan": "SuperGrok"
    },
    {
      "changeId": "change-7f021aeddba731b72a8bc19a",
      "id": "plan-0156",
      "kind": "plan",
      "vendor": "智谱 BigModel",
      "name": "GLM Coding V2 Max（老用户续费）",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://docs.bigmodel.cn/cn/coding-plan/notice/usage-revision"
      ],
      "fields": [
        "priceY"
      ],
      "before": {
        "priceY": null
      },
      "after": {
        "priceY": 375.2
      },
      "plan": "GLM Coding V2 Max（老用户续费）"
    },
    {
      "changeId": "change-91702b0165a550bf34053640",
      "id": "plan-0097",
      "kind": "plan",
      "vendor": "Cursor",
      "name": "Start（印度专属）",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://cursor.com/docs/models-and-pricing"
      ],
      "fields": [
        "cur",
        "priceM"
      ],
      "before": {
        "cur": "USD",
        "priceM": 8
      },
      "after": {
        "cur": "INR",
        "priceM": 649
      },
      "plan": "Start（印度专属）"
    },
    {
      "changeId": "change-925841d5dc56d189fb387575",
      "id": "plan-0138",
      "kind": "plan",
      "vendor": "Bolt.new",
      "name": "Pro",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://bolt.new/pricing"
      ],
      "fields": [
        "priceY"
      ],
      "before": {
        "priceY": null
      },
      "after": {
        "priceY": 18
      },
      "plan": "Pro"
    },
    {
      "changeId": "change-a34ee27e1bc9661f445d3d90",
      "id": "plan-0032",
      "kind": "plan",
      "vendor": "Z.ai",
      "name": "GLM Coding V3 Pro",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://z.ai/subscribe"
      ],
      "fields": [
        "priceM",
        "priceY"
      ],
      "before": {
        "priceM": 72,
        "priceY": 57.6
      },
      "after": {
        "priceM": 80,
        "priceY": 56
      },
      "plan": "GLM Coding V3 Pro"
    },
    {
      "changeId": "change-af5937b7992a03e140d43f17",
      "id": "硅基流动 SiliconFlow|Qwen/Qwen3.8-27B",
      "kind": "api",
      "vendor": "硅基流动 SiliconFlow",
      "name": "Qwen/Qwen3.8-27B",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://cloud-rd.siliconflow.cn/pricing"
      ],
      "fields": [
        "inCNY",
        "outCNY"
      ],
      "before": {
        "inCNY": 1.8,
        "outCNY": 14.4
      },
      "after": {
        "inCNY": 3,
        "outCNY": 12
      },
      "model": "Qwen/Qwen3.8-27B"
    },
    {
      "changeId": "change-c54acaae59581333114da30f",
      "id": "plan-0160",
      "kind": "plan",
      "vendor": "智谱 BigModel",
      "name": "GLM Coding Plan 团队标准版",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://bigmodel.cn/glm-coding"
      ],
      "fields": [
        "priceY"
      ],
      "before": {
        "priceY": null
      },
      "after": {
        "priceY": 538.2
      },
      "plan": "GLM Coding Plan 团队标准版"
    },
    {
      "changeId": "change-d0e2173924d84dc157d0522d",
      "id": "plan-0016",
      "kind": "plan",
      "vendor": "Google",
      "name": "Google AI Plus",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://blog.google/products-and-platforms/products/google-one/google-ai-plus-availability/",
        "https://one.google.com/about/google-ai-plans/"
      ],
      "fields": [
        "priceM"
      ],
      "before": {
        "priceM": 7.99
      },
      "after": {
        "priceM": 4.99
      },
      "plan": "Google AI Plus"
    },
    {
      "changeId": "change-d4c060d1224d283a18e43f10",
      "id": "plan-0149",
      "kind": "plan",
      "vendor": "腾讯云 CodeBuddy",
      "name": "企业旗舰版",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://www.codebuddy.cn/pricing/"
      ],
      "fields": [
        "plan",
        "priceM"
      ],
      "before": {
        "plan": "CodeBuddy 企业版",
        "priceM": null
      },
      "after": {
        "plan": "企业旗舰版",
        "priceM": 198
      },
      "plan": "企业旗舰版"
    },
    {
      "changeId": "change-feeb742795ef7f3f0970bf39",
      "id": "plan-0155",
      "kind": "plan",
      "vendor": "智谱 BigModel",
      "name": "GLM Coding V2 Pro（老用户续费）",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://docs.bigmodel.cn/cn/coding-plan/notice/usage-revision"
      ],
      "fields": [
        "priceY"
      ],
      "before": {
        "priceY": null
      },
      "after": {
        "priceY": 119.2
      },
      "plan": "GLM Coding V2 Pro（老用户续费）"
    },
    {
      "changeId": "change-ff4c63f9bac95e9d5c32726f",
      "id": "plan-0031",
      "kind": "plan",
      "vendor": "Z.ai",
      "name": "GLM Coding V3 Lite",
      "checkedAt": "2026-10-04",
      "sourceUrls": [
        "https://z.ai/subscribe"
      ],
      "fields": [
        "priceY"
      ],
      "before": {
        "priceY": 14.4
      },
      "after": {
        "priceY": 12.6
      },
      "plan": "GLM Coding V3 Lite"
    }
  ]
};
